embedding_model: sentence-transformers/all-MiniLM-L6-v2
generation_model: google/flan-t5-small
dim: 384
index_path: data/faiss_index/index.faiss
metadata_path: data/faiss_index/metadata.json
docs_folder: data/docs
